#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/467d3c25-acc2-4e37-be00-1605ead6742e # 
title: New API
version: v1

types: 
  Credentials: !include datatypes/RequiredCredentials.raml

/authorize/{envType}:
  uriParameters: 
    envType: 
      enum: [ DEV, PROD, TEST ]
  post:
     body:
       application/json:
        type: Credentials
     responses: 
       201:
         body: 
           application/json:
            example:
              message: Credentials accepted. Login successful.
       401:
        body: 
          application/json:
            example:
              message: Credentials incorrect. Login failed.
       400:
         body: 
           application/json:
             example:
               message: Kindly specify the credentials in the body in JSON.